services:
  #friendssharing:
   # container_name: friendssharing
   # build: .
   # ports:
    #  - 8080:8080
    #depends_on:
    #  db:
    #    condition: service_healthy
    #environment:
    #  - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/friendssharing

  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_DATABASE: friendssharing
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
        - 3306:3306


  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9000:80
    depends_on:
      db:
        condition: service_healthy